FROM golang:1.24.4-alpine3.22

RUN apk --no-cache add gcc g++ curl

# Variables that should be provided by the user
ARG WORKDIR_PATH
ARG BUILD_VERSION
ENV RESTAPI_PORT=8080

LABEL build_version=${BUILD_VERSION}

WORKDIR ${WORKDIR_PATH}
EXPOSE ${RESTAPI_PORT}

COPY go.* .
RUN go mod download

COPY ./config ./config
COPY ./src ./src

CMD ["go", "tool", "air", "-c", "./config/air.toml"]
