services:
  restapi:
    build:
      context: .
      dockerfile: ./src/cmd/restApi/.dev.dockerfile
      args:
        WORKDIR_PATH: ${PWD}
        BUILD_VERSION: ${BUILD_VERSION}
    volumes:
      - ./local:${PWD}/local
      - ./src:${PWD}/src
      - ${GOMODCACHE}:${GOMODCACHE}
      - ${GOCACHE}:${GOCACHE}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${RESTAPI_PORT}/build-version"]
      interval: 1m
      retries: 500
