# https://taskfile.dev

version: "3"

env:
  VERSION:
    sh: git rev-parse --short=4 HEAD
dotenv: ["env/.env"]

tasks:
  default:
    cmd: task --list-all

  stage:build:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.stage.yaml
      --project-directory ./
      build

  stage:up:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.stage.yaml
      --project-directory ./
      up

  stage:down:
    prompt: This is a dangerous command... Do you want to continue?
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.stage.yaml
      --project-directory ./
      down

  stage:start:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.stage.yaml
      --project-directory ./
      start

  stage:stop:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.stage.yaml
      --project-directory ./
      stop

  dev:build:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.dev.yaml
      --project-directory ./
      build

  dev:up:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.dev.yaml
      --project-directory ./
      up

  dev:down:
    prompt: This is a dangerous command... Do you want to continue?
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.dev.yaml
      --project-directory ./
      down

  dev:start:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.dev.yaml
      --project-directory ./
      start

  dev:stop:
    cmd: docker compose
      -f ./external/infrastructure/docker-compose.dev.yaml
      --project-directory ./
      stop

  pprof:cpu:
    cmd: go tool pprof -http=:3010 "$URL/debug/pprof/profile"

  pprof:heap:
    cmd: go tool pprof -http=:3010 "$URL/debug/pprof/heap"

  pprof:heap:collect:
    cmd: curl "$URL/debug/pprof/heap?gc=1" > "local/pprof/heap.$(date "+%y-%m-%d--%H-%M-%S")"

  pprof:heap:diff:
    cmd: go tool pprof -http=:3010 -diff_base $1 $2

  pprof:allocs:
    cmd: go tool pprof -http=:3010 "$URL/debug/pprof/allocs"

  pprof:goroutine:
    cmd: go tool pprof -http=:3010 "$URL/debug/pprof/goroutine"

  gorm:generate:
    cmd: go run ./src/cmd/gormgen

  openapi:lint:
    cmd: npx redocly lint ./external/openapi/cmd/openapi.yaml

  openapi:bundle:
    cmd: npx redocly bundle
      -o ./external/openapi/cmd/bundle.yaml
      ./external/openapi/cmd/openapi.yaml

  view:generate:
    cmd: go tool ogen
      --package viewgen
      --target ./src/shared/view/viewgen
      --clean ./external/openapi/cmd/bundle.yaml

  k6:generate:
    cmd: npx openapi-to-k6 -v
      --include-sample-script ./external/openapi/cmd/bundle.yaml
      test/
