// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package identity

import (
	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var UserHelper = struct {
	ID             field.Field[uuid.UUID]
	Username       field.String
	Email          field.String
	HashedPassword field.String
	Fullname       field.String
	Status         field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field[gorm.DeletedAt]
}{
	ID:             field.Field[uuid.UUID]{}.WithColumn("id"),
	Username:       field.String{}.WithColumn("username"),
	Email:          field.String{}.WithColumn("email"),
	HashedPassword: field.String{}.WithColumn("hashed_password"),
	Fullname:       field.String{}.WithColumn("fullname"),
	Status:         field.String{}.WithColumn("status"),
	CreatedAt:      field.Time{}.WithColumn("created_at"),
	UpdatedAt:      field.Time{}.WithColumn("updated_at"),
	DeletedAt:      field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
