name: giggler-golang-dev
services:
  webapi:
    build:
      context: ../..
      dockerfile: ./src/cmd/webapi/Dockerfile.dev
    environment:
      # Bind-mount Golang cache folders to speedup the Air rebuilds during runtime
      - GOMODCACHE=$GOMODCACHE
      - GOCACHE=$GOCACHE
    ports:
      - "2345:2345" # Delve debugger port
    volumes:
      # Bind-mount Golang cache folders to speedup the Air rebuilds during runtime
      - $GOMODCACHE:$GOMODCACHE
      - $GOCACHE:$GOCACHE
      # Bind-mount the source so Air can watch and rebuild on local edits
      - ${PWD}/src:${PWD}/src
