// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormModel

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJoke = "jokes"

// Joke mapped from table <jokes>
type Joke struct {
	ID          string         `gorm:"column:id;primaryKey" json:"id"`
	Title       string         `gorm:"column:title;not null" json:"title"`
	Text        string         `gorm:"column:text;not null" json:"text"`
	Explanation *string        `gorm:"column:explanation" json:"explanation"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID      string         `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName Joke's table name
func (*Joke) TableName() string {
	return TableNameJoke
}
