FROM golang:1.26-alpine AS builder

RUN apk --no-cache add curl

ARG WORKDIR_PATH
WORKDIR ${WORKDIR_PATH}

ARG GIGGLER_GOLANG_VERSION

ARG GOMODCACHE
ARG GOCACHE

COPY go.* .
# The buildtime cache mount
RUN --mount=type=cache,target=${GOMODCACHE} \
	go mod download

COPY ./src ./src

# The buildtime cache mount
RUN --mount=type=cache,target=${GOMODCACHE} \
	--mount=type=cache,target=${GOCACHE} \
	go build \
	-ldflags "-X giggler-golang/src/shared/version.Version=${GIGGLER_GOLANG_VERSION}" \
	-o /usr/local/bin/giggler-golang-webapi-${GIGGLER_GOLANG_VERSION} ./src/cmd/webapi

FROM alpine AS runner

RUN apk --no-cache add curl

ARG WORKDIR_PATH
WORKDIR ${WORKDIR_PATH}

ARG GIGGLER_GOLANG_VERSION
ENV GIGGLER_GOLANG_VERSION=${GIGGLER_GOLANG_VERSION}

COPY --from=builder /usr/local/bin/giggler-golang-webapi-${GIGGLER_GOLANG_VERSION} /usr/local/bin/giggler-golang-webapi-${GIGGLER_GOLANG_VERSION}

CMD ["sh", "-c", "exec /usr/local/bin/giggler-golang-webapi-${GIGGLER_GOLANG_VERSION}"]
