FROM golang:1.26-alpine AS builder

ARG WORKDIR_PATH
WORKDIR ${WORKDIR_PATH}

ARG GIGGLER_GOLANG_VERSION
ENV GIGGLER_GOLANG_VERSION=${GIGGLER_GOLANG_VERSION}

ENV GOMODCACHE="/root/go/pkg/mod"
ENV GOCACHE="/root/.cache/go-build"

RUN apk --no-cache add curl bash
RUN go install github.com/air-verse/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.* .
# The buildtime cache mount
RUN --mount=type=cache,target=${GOMODCACHE} \
    go mod download

COPY ./infra/local/.air.toml .
COPY ./src ./src

CMD ["air", "-c", ".air.toml"]
