services:
  restapi:
    build:
      context: .
      dockerfile: ./src/cmd/restApi/Dockerfile.release
      args:
        WORKDIR_PATH: ${PWD}
        BUILD_VERSION: ${BUILD_VERSION}
    volumes:
      - local:${PWD}/local
      - ./src:${PWD}/src
volumes:
  local:
