FROM golang:1.24-alpine
WORKDIR /workspace

RUN apk --no-cache add curl

RUN mkdir local

COPY go.* .
RUN go mod download

COPY ./.config/air.toml ./.config/air.toml
COPY ./src ./src

ENV API_PORT=3000
EXPOSE ${API_PORT}

CMD ["go", "tool", "air", "-c", "./.config/air.toml"]
