// Code generated by ogen, DO NOT EDIT.

package viewgen

import (
	"github.com/go-faster/errors"
)

func (s JokesSchema) Validate() error {
	alias := ([]JokeSchema)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
