// Code generated by ogen, DO NOT EDIT.

package viewgen

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginPostOperation    OperationName = "AuthLoginPost"
	AuthRefreshPostOperation  OperationName = "AuthRefreshPost"
	AuthRegisterPostOperation OperationName = "AuthRegisterPost"
	JokesDelOperation         OperationName = "JokesDel"
	JokesGetOperation         OperationName = "JokesGet"
	JokesPostOperation        OperationName = "JokesPost"
	JokesPutOperation         OperationName = "JokesPut"
	UserDelOperation          OperationName = "UserDel"
	UserGetOperation          OperationName = "UserGet"
	UserPutOperation          OperationName = "UserPut"
)
