// Code generated by ogen, DO NOT EDIT.

package viewgen

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginPostOperation    OperationName = "AuthLoginPost"
	AuthRefreshPostOperation  OperationName = "AuthRefreshPost"
	AuthRegisterPostOperation OperationName = "AuthRegisterPost"
	JokesGetOperation         OperationName = "JokesGet"
	UserDelOperation          OperationName = "UserDel"
	UserGetOperation          OperationName = "UserGet"
	UserJokesDelOperation     OperationName = "UserJokesDel"
	UserJokesGetOperation     OperationName = "UserJokesGet"
	UserJokesPostOperation    OperationName = "UserJokesPost"
	UserJokesPutOperation     OperationName = "UserJokesPut"
	UserPutOperation          OperationName = "UserPut"
)
