// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package jokeData

import (
	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var JokeHelper = struct {
	ID          field.Field[uuid.UUID]
	Title       field.String
	Text        field.String
	Explanation field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
	UserID      field.Field[uuid.UUID]
}{
	ID:          field.Field[uuid.UUID]{}.WithColumn("id"),
	Title:       field.String{}.WithColumn("title"),
	Text:        field.String{}.WithColumn("text"),
	Explanation: field.String{}.WithColumn("explanation"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:      field.Field[uuid.UUID]{}.WithColumn("user_id"),
}
