// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormModel

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserJoke = "user_jokes"

// UserJoke mapped from table <user_jokes>
type UserJoke struct {
	UserID    string         `gorm:"column:user_id;primaryKey" json:"user_id"`
	JokeID    string         `gorm:"column:joke_id;primaryKey" json:"joke_id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserJoke's table name
func (*UserJoke) TableName() string {
	return TableNameUserJoke
}
