// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormQuery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/abc-valera/giggler-golang/src/components/gormgen/gormModel"
)

func newUserJoke(db *gorm.DB, opts ...gen.DOOption) userJoke {
	_userJoke := userJoke{}

	_userJoke.userJokeDo.UseDB(db, opts...)
	_userJoke.userJokeDo.UseModel(&gormModel.UserJoke{})

	tableName := _userJoke.userJokeDo.TableName()
	_userJoke.ALL = field.NewAsterisk(tableName)
	_userJoke.UserID = field.NewString(tableName, "user_id")
	_userJoke.JokeID = field.NewString(tableName, "joke_id")
	_userJoke.CreatedAt = field.NewTime(tableName, "created_at")
	_userJoke.DeletedAt = field.NewField(tableName, "deleted_at")

	_userJoke.fillFieldMap()

	return _userJoke
}

type userJoke struct {
	userJokeDo userJokeDo

	ALL       field.Asterisk
	UserID    field.String
	JokeID    field.String
	CreatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (u userJoke) Table(newTableName string) *userJoke {
	u.userJokeDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userJoke) As(alias string) *userJoke {
	u.userJokeDo.DO = *(u.userJokeDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userJoke) updateTableName(table string) *userJoke {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewString(table, "user_id")
	u.JokeID = field.NewString(table, "joke_id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *userJoke) WithContext(ctx context.Context) *userJokeDo { return u.userJokeDo.WithContext(ctx) }

func (u userJoke) TableName() string { return u.userJokeDo.TableName() }

func (u userJoke) Alias() string { return u.userJokeDo.Alias() }

func (u userJoke) Columns(cols ...field.Expr) gen.Columns { return u.userJokeDo.Columns(cols...) }

func (u *userJoke) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userJoke) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["joke_id"] = u.JokeID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u userJoke) clone(db *gorm.DB) userJoke {
	u.userJokeDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userJoke) replaceDB(db *gorm.DB) userJoke {
	u.userJokeDo.ReplaceDB(db)
	return u
}

type userJokeDo struct{ gen.DO }

func (u userJokeDo) Debug() *userJokeDo {
	return u.withDO(u.DO.Debug())
}

func (u userJokeDo) WithContext(ctx context.Context) *userJokeDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userJokeDo) ReadDB() *userJokeDo {
	return u.Clauses(dbresolver.Read)
}

func (u userJokeDo) WriteDB() *userJokeDo {
	return u.Clauses(dbresolver.Write)
}

func (u userJokeDo) Session(config *gorm.Session) *userJokeDo {
	return u.withDO(u.DO.Session(config))
}

func (u userJokeDo) Clauses(conds ...clause.Expression) *userJokeDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userJokeDo) Returning(value interface{}, columns ...string) *userJokeDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userJokeDo) Not(conds ...gen.Condition) *userJokeDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userJokeDo) Or(conds ...gen.Condition) *userJokeDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userJokeDo) Select(conds ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userJokeDo) Where(conds ...gen.Condition) *userJokeDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userJokeDo) Order(conds ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userJokeDo) Distinct(cols ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userJokeDo) Omit(cols ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userJokeDo) Join(table schema.Tabler, on ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userJokeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userJokeDo) RightJoin(table schema.Tabler, on ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userJokeDo) Group(cols ...field.Expr) *userJokeDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userJokeDo) Having(conds ...gen.Condition) *userJokeDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userJokeDo) Limit(limit int) *userJokeDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userJokeDo) Offset(offset int) *userJokeDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userJokeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userJokeDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userJokeDo) Unscoped() *userJokeDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userJokeDo) Create(values ...*gormModel.UserJoke) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userJokeDo) CreateInBatches(values []*gormModel.UserJoke, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userJokeDo) Save(values ...*gormModel.UserJoke) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userJokeDo) First() (*gormModel.UserJoke, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gormModel.UserJoke), nil
	}
}

func (u userJokeDo) Take() (*gormModel.UserJoke, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gormModel.UserJoke), nil
	}
}

func (u userJokeDo) Last() (*gormModel.UserJoke, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gormModel.UserJoke), nil
	}
}

func (u userJokeDo) Find() ([]*gormModel.UserJoke, error) {
	result, err := u.DO.Find()
	return result.([]*gormModel.UserJoke), err
}

func (u userJokeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gormModel.UserJoke, err error) {
	buf := make([]*gormModel.UserJoke, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userJokeDo) FindInBatches(result *[]*gormModel.UserJoke, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userJokeDo) Attrs(attrs ...field.AssignExpr) *userJokeDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userJokeDo) Assign(attrs ...field.AssignExpr) *userJokeDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userJokeDo) Joins(fields ...field.RelationField) *userJokeDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userJokeDo) Preload(fields ...field.RelationField) *userJokeDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userJokeDo) FirstOrInit() (*gormModel.UserJoke, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gormModel.UserJoke), nil
	}
}

func (u userJokeDo) FirstOrCreate() (*gormModel.UserJoke, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gormModel.UserJoke), nil
	}
}

func (u userJokeDo) FindByPage(offset int, limit int) (result []*gormModel.UserJoke, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userJokeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userJokeDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userJokeDo) Delete(models ...*gormModel.UserJoke) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userJokeDo) withDO(do gen.Dao) *userJokeDo {
	u.DO = *do.(*gen.DO)
	return u
}
